version: '3.3'

services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-test-nginx
      args:
        BASE_IMAGE: ${IMAGE_NAME:-teslagov/jwt-nginx}:${IMAGE_VERSION:-latest}

  runner:
    build:
      context: .
      dockerfile: Dockerfile-test-runner
    environment:
      BASE_IMAGE: ${IMAGE_NAME:-teslagov/jwt-nginx}:${IMAGE_VERSION:-latest}
    
    depends_on:
      - nginx